config/routes.rb
Rails.application.routes.draw do
  
  root to: 'route_searches#suggest_route'
  devise_for :users
  resources :users

  resources :route_searches do 
    collection do
      post 'suggest_route'
      put 'best_route'
    end
  end  

  resources :ge_city_apis do
    collection do 
      get 'live_feed'
    end
  end

end

app/models/route_search.rb
class RouteSearch < ApplicationRecord
  require 'uri'
  require 'net/http'
  require 'json'
  
  def self.get_air_quality(lat, lng)
    url = URI("https://api.breezometer.com/baqi/?lat=#{lat}&lon=#{lng}&key=#{ENV['BREEZOMETER_API_KEY']}")
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new(url)
    request["cache-control"] = 'no-cache'
    request["postman-token"] = 'aa90a1e7-1f52-4d61-fc45-cdb05f4b50cd'
    res = http.request(request)
    response = JSON.parse(res.body)
    result = {}
    result['aqi'] = response['breezometer_aqi']
    result['color'] = response['breezometer_color']
    result['pollutant'] = response['dominant_pollutant_canonical_name']
    return result
  end

  # def self.get_best_route(routes)
  #   pollutant_list = ["co","no2","o3","pm10","pm25","so2"]
  #   puts "\n*"*10
  #   # puts routes
  #   puts "\n*"*10
    
  #   route_levels = []
  #   final_route = 0
  #   final_route_index = 0
  #   routes.each do |k, steps|
  #     step_weights = []
  #     total_time = 0
  #     pollutant_levels = {}
  #     pollutant_list.each do |pol|
  #       pollutant_levels[pol] = 0
  #     end
  #     steps.each do |step|
  #       # puts step
  #       lat = step['start_location']['lat']
  #       lng = step['start_location']['lng']
  #       air_quality = get_air_quality(lat,lng)
  #       puts "duration : #{step['duration']['text']}     pollutant : #{air_quality['pollutant']}"
  #       time = step['duration']['text'].split(' ')[0].to_i rescue 0
  #       pollutant_levels[air_quality['pollutant']]+=time
  #       total_time+=time
  #       step_weights << time*air_quality['aqi']
  #       puts "Step Weights : #{step_weights}"
  #       puts "#{air_quality['aqi']}"
  #     end
  #     route_levels << ((step_weights.sum)/total_time.to_f)
  #   end
  #   puts route_levels
  #   final_route_index = route_levels.index(route_levels.min) 
  #   return final_route_index
  # end

  def self.get_best_route(routes)
    pollutant_list = ["co","no2","o3","pm10","pm25","so2"]
    puts "\n*"*10
    # puts routes
    puts "\n*"*10
    
    route_levels = {}
    healthiest_route = []
    final_route = 0
    final_route_index = 0
    routes.each do |k, steps|
      step_weights = []
      total_time = 0
      pollutant_levels = {}
      pollutant_list.each do |pol|
        pollutant_levels[pol] = 0
      end
      aqi_index = []
      route_levels[k] = {}
      steps.each_with_index do |step, index|
        # puts step
        
        mod_val = (steps.length/10) + 1
        if(index%mod_val==0 && index != 0)  
          lat = step['start_location']['lat']
          lng = step['start_location']['lng']
          air_quality = get_air_quality(lat,lng)
          puts "duration : #{step['duration']['text']}     pollutant : #{air_quality['pollutant']}"
          time = step['duration']['text'].split(' ')[0].to_i rescue 0
          pollutant_levels[air_quality['pollutant']]+=time
          aqi_index << [air_quality['aqi'].to_s, lat, lng, air_quality['color'].split('#').last, air_quality['pollutant']]
          total_time+=time
          step_weights << time*air_quality['aqi']
          puts "Step Weights : #{step_weights}"
          puts "#{air_quality['aqi']}"
        end
      end
      route_levels[k]['pollutant_levels'] = pollutant_levels
      route_levels[k]['aqi_index'] = aqi_index 
      healthiest_route << ((step_weights.sum)/total_time.to_f)
    end
    final_route_index = healthiest_route.index(healthiest_route.max)
    route_levels['final_route'] = final_route_index 
    puts "\n$"*10
    puts route_levels
    puts "\n$"*10
    return route_levels
  end


end

app/controllers/route_searches_controller.rb
class RouteSearchesController < ApplicationController
  before_action :set_route_search, only: [:show, :edit, :update, :destroy]

  # GET /route_searches
  # GET /route_searches.json
  def index
    @route_searches = RouteSearch.all
  end

  # GET /route_searches/1
  # GET /route_searches/1.json
  def show
  end

  # GET /route_searches/new
  def new
    @route_search = RouteSearch.new
  end

  # GET /route_searches/1/edit
  def edit
  end

  # POST /route_searches
  # POST /route_searches.json
  def create
    @route_search = RouteSearch.new(route_search_params)

    respond_to do |format|
      if @route_search.save
        format.html { redirect_to @route_search, notice: 'Route search was successfully created.' }
        format.json { render :show, status: :created, location: @route_search }
      else
        format.html { render :new }
        format.json { render json: @route_search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /route_searches/1
  # PATCH/PUT /route_searches/1.json
  def update
    respond_to do |format|
      if @route_search.update(route_search_params)
        format.html { redirect_to @route_search, notice: 'Route search was successfully updated.' }
        format.json { render :show, status: :ok, location: @route_search }
      else
        format.html { render :edit }
        format.json { render json: @route_search.errors, status: :unprocessable_entity }
      end
    end
  end

  def suggest_route

  end

  def best_route
    puts "\n*"*10
    # puts params["legs"]
    puts "\n*"*10
    # puts params.keys
    puts "\n*"*10
    best_route = {}
    best_route = RouteSearch.get_best_route(params["legs"])
    respond_to do |format|
      format.json  { render :json => best_route }
    end
  end

  # DELETE /route_searches/1
  # DELETE /route_searches/1.json
  def destroy
    @route_search.destroy
    respond_to do |format|
      format.html { redirect_to route_searches_url, notice: 'Route search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route_search
      # @route_search = RouteSearch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_search_params
      params.require(:route_search).permit(:Source, :Destination)
    end
end

app/helpers/route_searches_helper.rb
module RouteSearchesHelper
end

app/views/route_searches/_form.html.haml
= simple_form_for(@route_search) do |f|
  = f.error_notification

  .form-inputs
    = f.input :Source
    = f.input :Destination

  .form-actions
    = f.button :submit

app/views/route_searches/edit.html.haml
%h1 Editing route_search

= render 'form'

= link_to 'Show', @route_search
\|
= link_to 'Back', route_searches_path

app/views/route_searches/index.html.haml
%h1 Listing route_searches

%table
  %thead
    %tr
      %th Source
      %th Destination
      %th
      %th
      %th

  %tbody
    - @route_searches.each do |route_search|
      %tr
        %td= route_search.Source
        %td= route_search.Destination
        %td= link_to 'Show', route_search
        %td= link_to 'Edit', edit_route_search_path(route_search)
        %td= link_to 'Destroy', route_search, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Route search', new_route_search_path

app/views/route_searches/new.html.haml
%h1 New route_search

= render 'form'

= link_to 'Back', route_searches_path

app/views/route_searches/show.html.haml
%p#notice= notice

%p
  %b Source:
  = @route_search.Source
%p
  %b Destination:
  = @route_search.Destination

= link_to 'Edit', edit_route_search_path(@route_search)
\|
= link_to 'Back', route_searches_path

app/views/route_searches/suggest_route.html.haml
.col-md-4
  = form_tag suggest_route_route_searches_path, method: :post, remote: true, html: {:id=> "form", :class=>"form"} do |f|
    .form-group.row
      %label.col-md-2.form-control-label From
      .col-md-10
        =text_field_tag :from, nil, class: 'from form-control input'
    .form-group.row
      %label.col-md-2.form-control-label To
      .col-md-10
        =text_field_tag :to, nil, class: 'to form-control input'
    .form-group.row
      %label.col-md-2.form-control-label Travel Mode
      .col-md-10
        =text_field_tag :mode, nil, class: 'mode form-control input'
    .clearfix
      = submit_tag "Go", class: "btn go btn-primary right" , style: "float: right; width: 6em"
#map{style: "height: 100%"}
%script{:src => "https://maps.google.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_JS_API_KEY']}&libraries=geometry", :type => "text/javascript"}
:javascript
  $(document).on("ready",function(e){
    var map;
    var directionsService;
    var polylines = [];
    var shadows = [];
    var data = [];
    var infowindow;
    var markers = [];
    function initialize_map(){
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 33.7757973, lng: -84.4015073},
            zoom: 12,
            mapTypeId: 'terrain'
        });

        directionsService = new google.maps.DirectionsService();
          // get the bounds of the polyline
          // http://stackoverflow.com/questions/3284808/getting-the-bounds-of-a-polyine-in-google-maps-api-v3
          google.maps.Polyline.prototype.getBounds = function(startBounds) {
              if(startBounds) {
                  var bounds = startBounds;
              }
              else {
                  var bounds = new google.maps.LatLngBounds();
              }
              this.getPath().forEach(function(item, index) {
                  bounds.extend(new google.maps.LatLng(item.lat(), item.lng()));
              });
              return bounds;
        };

        

        $(document).on('click','.go', function(){
          var from = $('.from').val();
          var to = $('.to').val(); 
          var mode = $('.mode').val();
          calcRoute(from, to, mode, map);
        });
      }

    function calcRoute(start, end, mode, map) {
      var request = {
          origin: start,
          destination: end,
          provideRouteAlternatives: true,
          unitSystem: google.maps.UnitSystem.METRIC,
          travelMode: google.maps.TravelMode[mode]
      };
      directionsService.route(request, function(response, status) {
          // clear former polylines
          for(var j in  polylines ) {
              polylines[j].setMap(null);
              shadows[j].setMap(null);
          }
          polylines = [];
          shadows = [];
          data = [];
          
          b = {}
          for(i in response.routes) {
              b[i] = response.routes[i].legs[0].steps
          }


          var route_index = 0
          console.log(b);
          if (status == google.maps.DirectionsStatus.OK) {
            $.ajax({
              url: "/route_searches/best_route.json",
              type: "PUT",
              data: JSON.stringify({'legs': b}),
              contentType: "application/json",
              success: function(route_values) {
                clearMarkers();
                console.log(route_values);
                route_index = route_values['final_route'];
                var locations = [];
                for(var j in route_values){
                  console.log("YOLO1");
                  for(var k in route_values[''+j]['aqi_index']){
                    console.log("YOLO2");
                    locations.push([route_values[''+j]['aqi_index'][k][1], route_values[''+j]['aqi_index'][k][2], route_values[''+j]['aqi_index'][k][0], route_values[''+j]['aqi_index'][k][3], route_values[''+j]['aqi_index'][k][4]]);
                  }
                }

                console.log(locations);
                
                for(var l in locations){
                  addMarker({lat: locations[l][0],lng: locations[l][1]}, locations[l][2], locations[l][3], locations[l][4],  map);
                }


                var bounds = new google.maps.LatLngBounds();
                for(var i in response.routes) {
                    // let's make the first suggestion highlighted;
                    var hide = (i==route_index ? false : true);
                    console.log(hide);
                    var shadow = drawPolylineShadow(response.routes[i].overview_path, '#666666');
                    var line = drawPolyline(response.routes[i].overview_path, '#0000ff', hide, map);
                    polylines.push(line);
                    shadows.push(shadow);
                    // let's add some data for the infoWindow
                    data.push({
                        distance: response.routes[i].legs[0].distance,
                        duration: response.routes[i].legs[0].duration,
                        end_address: response.routes[i].legs[0].end_address,
                        start_address: response.routes[i].legs[0].start_address,
                        end_location: response.routes[i].legs[0].end_location,
                        start_location: response.routes[i].legs[0].start_location
                    });
                    bounds = line.getBounds(bounds);

                    google.maps.event.addListener(shadow, 'click', function(e) {
                        // detect which route was clicked on
                        var index = shadows.indexOf(this);
                        highlightRoute(index, e, map);
                    });

                }
                map.fitBounds(bounds);
              
              }
            });

              
          }
      });
    }



    

    // Adds a marker to the map and push to the array.
    function addMarker(location, label, color, info, map) {
      var pinColor = color;
      var pinImage = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|" + pinColor,
          new google.maps.Size(21, 34),
          new google.maps.Point(0,0),
          new google.maps.Point(5, 34));
      var pinShadow = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_shadow",
          new google.maps.Size(40, 37),
          new google.maps.Point(0, 0),
          new google.maps.Point(12, 35));


      var marker = new google.maps.Marker({
        position: location,
        label: label,
        icon: pinImage,
        shadow: pinShadow,
        map: map
      });
      markers.push(marker);
    }

    // Sets the map on all markers in the array.
    function setMapOnAll(map) {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(map);
      }
    }

    // Removes the markers from the map, but keeps them in the array.
    function clearMarkers() {
      setMapOnAll(null);
    }

    // Shows any markers currently in the array.
    function showMarkers() {
      setMapOnAll(map);
    }

    // Deletes all markers in the array by removing references to them.
    function deleteMarkers() {
      clearMarkers();
      markers = [];
    }





    
    function highlightRoute(index, e, map) {
        for(var j in  polylines ) {
            if(j==index) {
                //var color = '#0000ff';
                polylines[j].setMap(map);
                // feel free to customise this string
                var contentString =
                    '<span>'+ data[j].distance.text +'</span><br/>'+
                    '<span>'+ data[j].duration.text +'</span><br/>'+
                    '<span>route: '+ j +'</span><br/>'+
                    //'From: <span>'+ data[j].start_address +'</span><br/>'+
                    //'To: <span>'+ data[j].end_address +'</span><br/>'+
                    '';
                if(e) {
                   var position = new google.maps.LatLng(e.latLng.lat(), e.latLng.lng());
                    // it may be needed to close the previous infoWindow
                    if(infowindow) {
                        infowindow.close();
                        infowindow = null;
                    }
                    infowindow = new google.maps.InfoWindow({
                        content: contentString,
                        position: position,
                        map: map
                    });
                    //infowindow.open(map, polylines[j]);
                }
            }
            else {
                polylines[j].setMap(null);
            }
        }
    }
    // returns a polyline.
    // if hide is set to true, the line is not put on the map
    function drawPolyline(path, color, hide, map) {
        var line = new google.maps.Polyline({
            path: path,
            strokeColor: color,
            strokeOpacity: 0.9,
            strokeWeight: 3
        });
        if(! hide) {
            line.setMap(map);
        }
        return line;
    }
    function drawPolylineShadow(path, color, hide) {
        var line = new google.maps.Polyline({
            path: path,
            strokeColor: color,
            strokeOpacity: 0.4,
            strokeWeight: 7
        });
        if(! hide) {
            line.setMap(map);
        }
        return line;
    }
    google.maps.event.addDomListener(window, 'load', initialize_map);
  });

  